import { ThemeProvider } from "@/contexts/ThemeProvider";

import "@/styles/globals.css";

import type { Metadata } from "next";
import { Londrina_Solid, Poppins } from "next/font/google";
import Link from "next/link";

import { ThemeButton } from "@/components/molecules/ThemeButton";
import Squiggle from "@/components/Squiggle";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "400", "600", "700", "800"],
  variable: "--font-body",
});

const heading = Londrina_Solid({
  subsets: ["latin"],
  weight: ["400", "900"],
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${heading.variable} ${poppins.variable} `}
    >
      <body className={`font-body min-h-screen`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <header>
            <nav className="flex justify-between container py-5">
              <h1 className=" scroll-m-20 text-2xl font-bold lg:text-3xl">
                Expresso
              </h1>
              <div className="flex gap-10 items-center">
                <Link
                  href="/author/"
                  className="scroll-m-20 text-lg lg:text-xl font-semibold tracking-tight"
                >
                  Write
                </Link>
                <ThemeButton />
              </div>
            </nav>
            <div className="w-full border-b-2 border-foreground squiggle" />
          </header>
          <main>{children}</main>
        </ThemeProvider>
        <Squiggle />
      </body>
    </html>
  );
}
